spring.application.name=payments 

rabbit.queue.payment=${RABBIT_QUEUE_NAME_PAYMENT}
server.port=${APP_PAYMENTS_PORT}
spring.datasource.url=${DB_HOST_LOCAL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
#

spring.rabbitmq.host=${RABBIT_HOST}
spring.rabbitmq.port=${RABBIT_PORT}
spring.rabbitmq.username=${RABBIT_USER}

spring.rabbitmq.password=${RABBIT_PASS}
spring.rabbitmq.listener.simple.concurrency=5
spring.rabbitmq.listener.simple.max-concurrency=10



#---
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=15
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
#--





server.tomcat.threads.max=200
server.tomcat.threads.min-spare=20



#


server.tomcat.connection-timeout=30s
spring.mvc.async.request-timeout=30s