spring.application.name=kafka-event-router-camel
server.port=${KAFKA_PORT}

eventos.dlq.json2=${eventos.dlq.json2}
eventos.dlq.json1=${eventos.dlq.json1}
eventos.dlq.xml=${eventos.dlq.xml}
mi.topico.entrada=${mi.topico.entrada}




camel.springboot.main-run-controller=true

kafka.group.router=kafka-event-router-group

# ===================================================================
# CONFIGURACIÓN DE LOS MOCKS (SIMULACIONES LOCALES)
# ===================================================================
# Simula la salida XML guardando los archivos en una carpeta local

#entorno config
endpoint.salida.xml=${SALIDA_XML}
# Simulan las salidas JSON imprimiendo todo el contenido en tu consola
endpoint.salida.json.uno=${SALIDA_UNO}
endpoint.salida.json.dos=${SALIDA_DOS}


# ===================================================================
# CONFIGURACIÓN DE APACHE KAFKA (CAMEL COMPONENT)
# ===================================================================
# Dirección de los brokers de Kafka (separa por comas si son varios)
#iria a variable de entorno..

#entorno config
camel.component.kafka.brokers=${KAFKA_BROKERS}


# Identificador único del grupo de consumidores
camel.component.kafka.group-id=kafka-event-router-group

# Estrategia de lectura si no hay un offset inicial guardado (latest o earliest)
camel.component.kafka.auto-offset-reset=earliest

# Habilita el guardado automático de offsets leídos
camel.component.kafka.auto-commit-enable=true
camel.component.kafka.auto-commit-interval-ms=5000

# ===================================================================
# OPTIMIZACIÓN DE RENDIMIENTO Y CONCURRENCIA
# ===================================================================
# Número de hilos/consumidores concurrentes por ruta de Kafka
camel.component.kafka.consumers-count=2

# Tamaño máximo de registros recuperados en una sola solicitud de poll
camel.component.kafka.max-poll-records=500

# Tiempo máximo (en ms) que el consumidor espera en el poll si no hay datos
camel.component.kafka.poll-timeout-ms=5000

# ===================================================================
# RESILIENCIA Y MANEJO DE ERRORES (PRODUCTOR)
# ===================================================================
# Confirmación de recepción exigida al broker (1 = líder, all = réplicas completas)
camel.component.kafka.acks=all

# Número de reintentos automáticos si el envío de un evento falla
camel.component.kafka.retries=3

# Tiempo de espera (en ms) antes de que un envío falle por timeout
camel.component.kafka.request-timeout-ms=30000


# ===================================================================
# DETECCIÓN Y UBICACIÓN DE RUTAS
# ===================================================================
camel.springboot.xml-routes=classpath:camel/*.xml
camel.springboot.routes-include-pattern=classpath:camel/*.yaml

# ===================================================================
# GESTIÓN Y MONITOREO (PRODUCCIÓN)
# ===================================================================

camel.springboot.message-history=true
camel.springboot.jmx-enabled=true
camel.springboot.tracing=false

# ===================================================================
# CONTROL DE CICLO DE VIDA Y APAGADO SEGURO (SHUTDOWN)
# ===================================================================
# Tiempo máximo (en segundos) para esperar que las rutas infladas terminen de procesar antes de apagar
camel.springboot.shutdown-timeout=10

# Detiene el inicio de la app si una ruta crítica falla al arrancar
camel.springboot.auto-startup=true

# ===================================================================
# SUPERVISIÓN Y REINTENTOS DE RUTAS
# ===================================================================
# Activa el supervisor para reintentar arrancar rutas si el broker/BD está caído
camel.springboot.route-controller-supervise-enabled=true

# Tiempo de espera antes del primer reintento de arranque
camel.springboot.route-controller-initial-delay=5s

# Número máximo de intentos de arranque antes de marcar la ruta como fallida
camel.springboot.route-controller-back-off-max-attempts=5

# ===================================================================
# CONFIGURACIÓN DEL CIRCUIT BREAKER (RESILIENCE4J)
# ===================================================================
# Ventana de tiempo en segundos para evaluar las fallas
camel.resilience4j.sliding-window-size=10
# Porcentaje de fallas (ej. 50%) para abrir el circuito
camel.resilience4j.failure-rate-threshold=50
# Tiempo que el circuito permanece abierto antes de intentar volver a cerrar (semi-abierto)
camel.resilience4j.wait-duration-in-open-state=10s
# Habilita el límite de tiempo de ejecución para el bloque protegido
camel.resilience4j.timeout-enabled=true
# Si la petición tarda más de este tiempo (ej. 8 segundos), el Circuit Breaker interrumpe la llamada y dispara
camel.resilience4j.timeout-duration=8s
# ===================================================================
# CONFIGURACIÓN DEL COMPONENTE SEDA
# ===================================================================
# Tamaño máximo de mensajes en la cola antes de bloquear al productor
camel.component.seda.queue-size=1000
# Número de hilos concurrentes procesando cada cola SEDA
seda.concurrent.consumers=2

# ===================================================================
# CONFIGURACIÓN DE TIMEOUTS PARA LOS ENDPOINTS HTTP (JSON)
# ===================================================================
# Tiempo máximo (en milisegundos) para establecer la conexión con el servidor externo (5 segundos)
camel.component.http.connect-timeout=5000

# Tiempo máximo de espera para recibir una respuesta tras conectarse (10 segundos)
camel.component.http.socket-timeout=10000

